spring.application.name=employee-management-API

spring.datasource.url=jdbc:mysql://localhost:3306/employeesDB
spring.datasource.username=javarudra
spring.datasource.password=2007
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
